/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import javax.swing.*;
import javax.swing.tree.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import SYS.*;
import Audit.Audit;
import DS.*;

/**
 *
 * @author 58414
 */
public class Admin extends javax.swing.JFrame {

    private final FileSystem fileSystem;
    private Directory currentDirectory;
    private Directory selectedDirectory;
    private final Audit audit;
    private TreeManager treeManager;
    
    // Archivo seleccionado para eliminar
    private Directory dirOfFileToDelete = null;   // directorio donde está
    private MyFile fileToDelete = null;           // archivo a borrar
    
    // Directorio seleccionado para eliminar
    private Directory dirToDelete = null;

    public Admin(FileSystem fileSystem, Directory startDir, Audit audit, TreeManager treeManager) {
    this.fileSystem = fileSystem;
    this.currentDirectory = startDir;
    this.audit = audit;
    this.treeManager = treeManager;

    initComponents();

    this.treeManager.buildTree();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameFile = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dirButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        selArch = new javax.swing.JButton();
        delArch = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        newNameFile = new javax.swing.JTextField();
        updArch = new javax.swing.JButton();
        sizeFile = new javax.swing.JSpinner();
        colorCmb = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        directoryName = new javax.swing.JTextField();
        createDir = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        selDir = new javax.swing.JButton();
        delDir = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        newDirectoryName = new javax.swing.JTextField();
        updDir = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        showTree = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Archivos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel2.setText("Crear archivo");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Tamaño:");

        jLabel5.setText("Color:");

        nameFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFileActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel6.setText("Eliminar archivo");

        dirButton.setText("Seleccionar directorio");
        dirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dirButtonActionPerformed(evt);
            }
        });

        jButton3.setText("Crear archivo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        selArch.setText("Seleccionar");
        selArch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selArchActionPerformed(evt);
            }
        });

        delArch.setText("Eliminar archivo");
        delArch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delArchActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel7.setText("Actualizar archivo");

        jLabel8.setText("Actualizar nombre del archivo:");

        newNameFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newNameFileActionPerformed(evt);
            }
        });

        updArch.setText("Actualizar archivo");
        updArch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updArchActionPerformed(evt);
            }
        });

        colorCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Azul", "Rojo", "Amarillo", "Verde" }));
        colorCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorCmbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(selArch)
                        .addGap(48, 48, 48)
                        .addComponent(delArch)
                        .addGap(87, 87, 87))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(colorCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nameFile, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addComponent(sizeFile))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(dirButton)
                                .addGap(30, 30, 30))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(newNameFile, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 45, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(185, 185, 185))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(updArch)
                        .addGap(175, 175, 175))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nameFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(sizeFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(colorCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(selArch)
                            .addComponent(delArch)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(dirButton)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newNameFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updArch)
                .addGap(19, 19, 19))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Directorios", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel9.setText("Crear directorio");

        jLabel10.setText("Nombre del nuevo directorio:");

        directoryName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directoryNameActionPerformed(evt);
            }
        });

        createDir.setText("Crear directorio");
        createDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDirActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel11.setText("Eliminar directorio");

        selDir.setText("Seleccionar directorio");
        selDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selDirActionPerformed(evt);
            }
        });

        delDir.setText("Eliminar directorio");
        delDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delDirActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel12.setText("Actualizar directorio");

        jLabel13.setText("Actualizar nombre del directorio:");

        newDirectoryName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDirectoryNameActionPerformed(evt);
            }
        });

        updDir.setText("Actualizar directorio");
        updDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updDirActionPerformed(evt);
            }
        });

        jButton2.setText("Directorio Padre");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(59, 59, 59)
                .addComponent(createDir)
                .addGap(74, 74, 74))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newDirectoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(directoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(selDir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(delDir, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(updDir)
                        .addGap(151, 151, 151))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(171, 171, 171))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(directoryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createDir)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(delDir)
                    .addComponent(selDir))
                .addGap(34, 34, 34)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newDirectoryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updDir)
                .addGap(20, 20, 20))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Modo Administrador");

        jButton1.setText("Cambiar Modo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton11.setText("Cargar versiones");

        jButton12.setText("Ver bloques");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        showTree.setText("Ver Sistema");
        showTree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTreeActionPerformed(evt);
            }
        });

        jButton4.setText("Tabla de Archivos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addComponent(showTree)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(406, 406, 406))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(402, 402, 402))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(434, 434, 434))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton11)
                            .addComponent(showTree)
                            .addComponent(jButton12))
                        .addGap(32, 32, 32)))
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MainFrame main = new MainFrame();
        this.setVisible(false);
        main.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String name = nameFile.getText().toUpperCase().strip();
        if (name.isEmpty()) {
            // Validación para que el nombre no sea vacío.
            javax.swing.JOptionPane.showMessageDialog(this, "Ingresa un nombre.");
            return;
        }

        int size = 0;
        try {
            size = ((Number) sizeFile.getValue()).intValue();
        } catch (ClassCastException e) {
            JOptionPane.showMessageDialog(this, "El tamaño debe ser un número entero");
            return;
        }
        if (size <= 0) {
            JOptionPane.showMessageDialog(this, "El tamaño en bloques debe ser mayor que 0");
            return;
        }

        String color = ((String) colorCmb.getSelectedItem()).toUpperCase().strip();
 
        Directory target = selectedDirectory;
        String user = System.getProperty("user.name");

        MyFile file = fileSystem.addFile(name, size, color, target, user);

        if (file != null) {
            JOptionPane.showMessageDialog(this,
                    "Archivo creado correctamente",
                    "Éxito", JOptionPane.INFORMATION_MESSAGE);

            // Refrescar JTree
            treeManager.refresh();

            // Limpiar campos
            nameFile.setText("");
            sizeFile.setValue(1);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void nameFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFileActionPerformed

    private void newNameFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newNameFileActionPerformed

    }//GEN-LAST:event_newNameFileActionPerformed

    private void updArchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updArchActionPerformed
        String newName = newNameFile.getText().toUpperCase().strip();
        if (newName.isEmpty()) {
            // Validación para que el nombre no sea vacío.
            javax.swing.JOptionPane.showMessageDialog(this, "Ingresa un nombre.");
            return;
        }
        treeManager.openFileChooser((Directory dir, MyFile file) -> {
            // Este código se ejecuta cuando el usuario hace clic en "Seleccionar" en el chooser

            String user = System.getProperty("user.name");

            boolean ok = fileSystem.renameFile(dir, file, newName, user);

            if (ok) {
                JOptionPane.showMessageDialog(
                        this,
                        "Archivo renombrado correctamente:\n"
                        + "Nuevo nombre: " + newName
                        + "\nDirectorio: " + dir.getRute(),
                        "Éxito",
                        JOptionPane.INFORMATION_MESSAGE
                );

                // Limpiar campo y refrescar vista
                newNameFile.setText("");
                treeManager.refresh();
            } else {
                JOptionPane.showMessageDialog(
                        this,
                        "No se pudo renombrar el archivo.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        });
    }//GEN-LAST:event_updArchActionPerformed

    private void updDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updDirActionPerformed
        String newName = newDirectoryName.getText().toUpperCase().strip();
        if (newName.isEmpty()) {
            // Validación para que el nombre no sea vacío.
            javax.swing.JOptionPane.showMessageDialog(this, "Ingresa un nombre.");
            return;
        }
        treeManager.openDirectoryChooser(selectedDir -> {

            String user = System.getProperty("user.name");

            boolean ok = fileSystem.renameDirectory(selectedDir, newName, user);

            if (ok) {
                JOptionPane.showMessageDialog(this,
                        "Directorio renombrado a:\n" + newName,
                        "Éxito",
                        JOptionPane.INFORMATION_MESSAGE
                );

                // limpiar campo
                newDirectoryName.setText("");

                // actualizar vista
                treeManager.refresh();

            } else {
                JOptionPane.showMessageDialog(
                        this,
                        "No se pudo renombrar el directorio.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
            }
        });
    }//GEN-LAST:event_updDirActionPerformed

    private void newDirectoryNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDirectoryNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newDirectoryNameActionPerformed

    private void createDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDirActionPerformed
        String nameDir = directoryName.getText().toUpperCase().strip();
        if (nameDir.isEmpty()) {
            // Validación para que el nombre no sea vacío.
            javax.swing.JOptionPane.showMessageDialog(this, "Ingresa un nombre.");
            return;
        }

        // Crear directorio
        Directory parent = (selectedDirectory != null) ? selectedDirectory : currentDirectory;
        Directory newDir = fileSystem.addDirectory(nameDir, parent, System.getProperty("user.name"));

        // Actualizar el JTree
        treeManager.refresh();

        JOptionPane.showMessageDialog(this, "Directorio '" + nameDir + "' creado con éxito.");

        // Limpiar el campo
        directoryName.setText("");
        
    }//GEN-LAST:event_createDirActionPerformed

    private void directoryNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directoryNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_directoryNameActionPerformed

    private void showTreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTreeActionPerformed
        // TODO add your handling code here:
        treeManager.refresh();
        treeManager.showTree();
    }//GEN-LAST:event_showTreeActionPerformed

    private void colorCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorCmbActionPerformed

    private void dirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dirButtonActionPerformed
        // TODO add your handling code here:
        treeManager.openDirectoryChooser(dir -> {
            selectedDirectory = dir;
            JOptionPane.showMessageDialog(this,
                    "Directorio seleccionado:\n" + dir.getRute(),
                    "Directorio elegido",
                    JOptionPane.INFORMATION_MESSAGE);
        });
    }//GEN-LAST:event_dirButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        treeManager.openDirectoryChooser(dir -> {
            selectedDirectory = dir;
            JOptionPane.showMessageDialog(this,
                    "Directorio seleccionado:\n" + dir.getRute(),
                    "Directorio elegido",
                    JOptionPane.INFORMATION_MESSAGE);
        });
    }//GEN-LAST:event_jButton2ActionPerformed

    private void selArchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selArchActionPerformed
        // TODO add your handling code here:
        treeManager.openFileChooser((dir, file) -> {
            dirOfFileToDelete = dir;
            fileToDelete = file;

            JOptionPane.showMessageDialog(
                    this,
                    "Archivo seleccionado:\n" + file.getName()
                    + "\nDirectorio: " + dir.getRute(),
                    "Archivo a eliminar",
                    JOptionPane.INFORMATION_MESSAGE
            );
        });
    }//GEN-LAST:event_selArchActionPerformed

    private void delArchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delArchActionPerformed
        // TODO add your handling code here:
        if (fileToDelete == null || dirOfFileToDelete == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Primero selecciona un archivo a eliminar.",
                    "Ningún archivo seleccionado",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        String user = System.getProperty("user.name");
        boolean ok = fileSystem.deleteFile(dirOfFileToDelete, fileToDelete, user);

        if (ok) {
            JOptionPane.showMessageDialog(
                    this,
                    "Archivo '" + fileToDelete.getName() + "' eliminado correctamente.",
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE
            );

            // limpiar selección
            fileToDelete = null;
            dirOfFileToDelete = null;

            // refrescar árbol visual
            treeManager.refresh();
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "No se pudo eliminar el archivo.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_delArchActionPerformed

    private void selDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selDirActionPerformed
        // TODO add your handling code here:
        treeManager.openDirectoryChooser(dir -> {
            dirToDelete = dir;

            JOptionPane.showMessageDialog(
                    this,
                    "Directorio seleccionado para eliminar:\n" + dir.getRute(),
                    "Directorio seleccionado",
                    JOptionPane.INFORMATION_MESSAGE
            );
        });
    }//GEN-LAST:event_selDirActionPerformed

    private void delDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delDirActionPerformed
        // TODO add your handling code here:
        if (dirToDelete == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Primero selecciona un directorio a eliminar.",
                    "Ningún directorio seleccionado",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // Evitar borrar la raíz
        if (dirToDelete == fileSystem.getRoot()) {
            JOptionPane.showMessageDialog(
                    this,
                    "No se puede eliminar el directorio raíz.",
                    "Operación no permitida",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "¿Seguro que deseas eliminar el directorio:\n" + dirToDelete.getRute()
                + "\n y todo su contenido?",
                "Confirmar eliminación",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        String user = System.getProperty("user.name");
        boolean ok = fileSystem.deleteDirectory(dirToDelete, user);

        if (ok) {
            JOptionPane.showMessageDialog(
                    this,
                    "Directorio eliminado correctamente.",
                    "Éxito",
                    JOptionPane.INFORMATION_MESSAGE
            );
            dirToDelete = null;
            treeManager.refresh();  // refrescamos el JTree
        } else {
            JOptionPane.showMessageDialog(
                    this,
                    "No se pudo eliminar el directorio.",
                    "Error",
                    JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_delDirActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        FilesTable win = new FilesTable(fileSystem);
        win.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        BlocksWindow bw = new BlocksWindow(fileSystem);
        bw.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Admin().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> colorCmb;
    private javax.swing.JButton createDir;
    private javax.swing.JButton delArch;
    private javax.swing.JButton delDir;
    private javax.swing.JButton dirButton;
    private javax.swing.JTextField directoryName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField nameFile;
    private javax.swing.JTextField newDirectoryName;
    private javax.swing.JTextField newNameFile;
    private javax.swing.JButton selArch;
    private javax.swing.JButton selDir;
    private javax.swing.JButton showTree;
    private javax.swing.JSpinner sizeFile;
    private javax.swing.JButton updArch;
    private javax.swing.JButton updDir;
    // End of variables declaration//GEN-END:variables
}
