/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import javax.swing.*;
import SYS.*;
import Audit.Audit;
import com.google.gson.Gson;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author 58414
 */
public class Admin extends javax.swing.JFrame {

    private FileSystem fileSystem;
    private Directory currentDirectory;
    private Directory selectedDirectory;
    private final Audit audit;
    private TreeManager treeManager;
    
    // Archivo seleccionado para eliminar
    private Directory dirOfFileToDelete = null;   // directorio donde está
    private MyFile fileToDelete = null;           // archivo a borrar
    
    // Directorio seleccionado para eliminar
    private Directory dirToDelete = null;

    public Admin(FileSystem fileSystem, Directory startDir, Audit audit, TreeManager treeManager) {
        this.fileSystem = fileSystem;
        this.currentDirectory = startDir;
        this.audit = audit;
        this.treeManager = treeManager;
        
        initComponents();
        
        this.treeManager.buildTree();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nameFile = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        dirButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        selArch = new javax.swing.JButton();
        delArch = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        newNameFile = new javax.swing.JTextField();
        updArch = new javax.swing.JButton();
        sizeFile = new javax.swing.JSpinner();
        colorCmb = new javax.swing.JComboBox<>();
        levelComb = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        directoryName = new javax.swing.JTextField();
        createDir = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        selDir = new javax.swing.JButton();
        delDir = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        newDirectoryName = new javax.swing.JTextField();
        updDir = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        showTree = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Archivos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel2.setText("Crear archivo");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Tamaño:");

        jLabel5.setText("Color:");

        nameFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameFileActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel6.setText("Eliminar archivo");

        dirButton.setText("Seleccionar directorio");
        dirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dirButtonActionPerformed(evt);
            }
        });

        jButton3.setText("Crear archivo");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        selArch.setText("Seleccionar");
        selArch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selArchActionPerformed(evt);
            }
        });

        delArch.setText("Eliminar archivo");
        delArch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delArchActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel7.setText("Actualizar archivo");

        jLabel8.setText("Actualizar nombre del archivo:");

        newNameFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newNameFileActionPerformed(evt);
            }
        });

        updArch.setText("Actualizar archivo");
        updArch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updArchActionPerformed(evt);
            }
        });

        colorCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Azul", "Rojo", "Amarillo", "Verde" }));
        colorCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorCmbActionPerformed(evt);
            }
        });

        levelComb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Publico", "Privado" }));

        jLabel14.setText("Nivel:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(newNameFile, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 45, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(levelComb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(colorCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nameFile, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                    .addComponent(sizeFile))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(dirButton)
                                .addGap(30, 30, 30))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(selArch)
                .addGap(49, 49, 49)
                .addComponent(delArch)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(updArch)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(187, 187, 187))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(nameFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(sizeFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(colorCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(dirButton)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(levelComb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(23, 23, 23)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delArch)
                    .addComponent(selArch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(newNameFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updArch)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Directorios", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel9.setText("Crear directorio");

        jLabel10.setText("Nombre del nuevo directorio:");

        directoryName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                directoryNameActionPerformed(evt);
            }
        });

        createDir.setText("Crear directorio");
        createDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDirActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel11.setText("Eliminar directorio");

        selDir.setText("Seleccionar directorio");
        selDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selDirActionPerformed(evt);
            }
        });

        delDir.setText("Eliminar directorio");
        delDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delDirActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel12.setText("Actualizar directorio");

        jLabel13.setText("Actualizar nombre del directorio:");

        newDirectoryName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newDirectoryNameActionPerformed(evt);
            }
        });

        updDir.setText("Actualizar directorio");
        updDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updDirActionPerformed(evt);
            }
        });

        jButton2.setText("Directorio Padre");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(59, 59, 59)
                .addComponent(createDir)
                .addGap(74, 74, 74))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newDirectoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(directoryName, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(selDir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(delDir, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(updDir)
                        .addGap(151, 151, 151))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(140, 140, 140))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(171, 171, 171))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(directoryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createDir)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(delDir)
                    .addComponent(selDir))
                .addGap(34, 34, 34)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newDirectoryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updDir)
                .addGap(20, 20, 20))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Modo Administrador");

        jButton1.setText("Cambiar Modo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton11.setText("Cargar versiones");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Ver bloques");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        showTree.setText("Ver Sistema");
        showTree.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showTreeActionPerformed(evt);
            }
        });

        jButton4.setText("Tabla de Archivos");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Guardar version");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(76, 76, 76)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128)
                        .addComponent(showTree)
                        .addGap(93, 93, 93)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(406, 406, 406))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(402, 402, 402))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(434, 434, 434))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton12)
                    .addComponent(showTree)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton11)
                        .addComponent(jButton5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MainFrame main = new MainFrame();
        this.setVisible(false);
        main.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String name = nameFile.getText().toUpperCase().strip();
        if (name.isEmpty()) {
            // Validación para que el nombre no sea vacío.
            javax.swing.JOptionPane.showMessageDialog(this, "Ingresa un nombre.");
            return;
        }

        int size = 0;
        try {
            size = ((Number) sizeFile.getValue()).intValue();
        } catch (ClassCastException e) {
            JOptionPane.showMessageDialog(this, "El tamaño debe ser un número entero");
            return;
        }
        if (size <= 0) {
            JOptionPane.showMessageDialog(this, "El tamaño en bloques debe ser mayor que 0");
            return;
        }

        String color = ((String) colorCmb.getSelectedItem()).toUpperCase().strip();
 
        Directory target = selectedDirectory;
        String user = System.getProperty("user.name");
        
        String level = ((String) levelComb.getSelectedItem()).strip();
        
        boolean isPublic = level.equals("Publico");

        MyFile file = fileSystem.addFile(name, size, color, target, user, isPublic, null);

        if (file != null) {
            JOptionPane.showMessageDialog(this,
                    "Archivo creado correctamente",
                    "Éxito", JOptionPane.INFORMATION_MESSAGE);

            // Refrescar JTree
            treeManager.refresh();

            // Limpiar campos
            nameFile.setText("");
            sizeFile.setValue(1);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void nameFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameFileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameFileActionPerformed

    private void newNameFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newNameFileActionPerformed
        
    }//GEN-LAST:event_newNameFileActionPerformed

    private void updArchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updArchActionPerformed
     
    String newName = newNameFile.getText().toUpperCase().strip();

    if (newName.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingresa un nombre válido.");
        return;
    }

    treeManager.openFileChooser((Directory dir, MyFile file) -> {

        // Validar selección
        if (file == null || dir == null) {
            JOptionPane.showMessageDialog(
                    this,
                    "Primero selecciona un archivo.",
                    "Ningún archivo seleccionado",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        String user = System.getProperty("user.name");

        // Verificar si ya existe un archivo con ese nombre en el directorio
        Object filesObj = dir.getFiles();
        if (filesObj instanceof MyFile[]) {
            for (MyFile f : (MyFile[]) filesObj) {
                if (f.getName().equalsIgnoreCase(newName)) {
                    JOptionPane.showMessageDialog(this, "Ya existe un archivo con ese nombre.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
        } else if (filesObj instanceof java.util.Collection<?>) {
            for (Object o : (java.util.Collection<?>) filesObj) {
                if (o instanceof MyFile f) {
                    if (f.getName().equalsIgnoreCase(newName)) {
                        JOptionPane.showMessageDialog(this, "Ya existe un archivo con ese nombre.", "Error", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                }
            }
        }

        // Renombrar en memoria
        file.setName(newName);

        // Guardar cambios en el MISMO JSON
        fileSystem.saveState("");

        JOptionPane.showMessageDialog(
                this,
                "Archivo renombrado correctamente.\nNuevo nombre: " + newName,
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE
        );

        // Limpiar campo y refrescar
        newNameFile.setText("");
        treeManager.refresh();
    });

    }//GEN-LAST:event_updArchActionPerformed

    private void updDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updDirActionPerformed
        String newName = newDirectoryName.getText().toUpperCase().strip();
        if (newName.isEmpty()) {
            // Validación para que el nombre no sea vacío.
            javax.swing.JOptionPane.showMessageDialog(this, "Ingresa un nombre.");
            return;
        }
        treeManager.openDirectoryChooser(dir -> {
        if (dir == null) {
        JOptionPane.showMessageDialog(
                this,
                "Primero selecciona un directorio.",
                "Ningún directorio seleccionado",
                JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    // Validar que no exista otro directorio con el mismo nombre en la misma carpeta padre
    Directory parent = dir.getFather(); // suponiendo que tienes getFather()
    if (parent != null) {
        Object subsObj = parent.getSubdirectories();
        boolean nameExists = false;

        if (subsObj instanceof Directory[]) {
            for (Directory d : (Directory[]) subsObj) {
                if (d.getName().equalsIgnoreCase(newName)) {
                    nameExists = true;
                    break;
                }
            }
        } else if (subsObj instanceof java.util.Collection<?>) {
            for (Object o : (java.util.Collection<?>) subsObj) {
                if (o instanceof Directory d && d.getName().equalsIgnoreCase(newName)) {
                    nameExists = true;
                    break;
                }
            }
        }

        if (nameExists) {
            JOptionPane.showMessageDialog(
                    this,
                    "Ya existe un directorio con ese nombre en esta carpeta.",
                    "Nombre duplicado",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }
    }
    dir.setName(newName); // renombrar en memoria

    // Guardar en el JSON que contiene este directorio
    Gson gson = new Gson();
//    JsonObject dirJson = serializeDirectoryGson(dir);
//    String jsonPath = dir.getJsonPath(); // asegurarse de que Directory tiene un atributo con la ruta del JSON
//    if (jsonPath == null || jsonPath.isEmpty()) {
//    JOptionPane.showMessageDialog(this, "No se encontró el archivo JSON del directorio.", "Error", JOptionPane.ERROR_MESSAGE);
//    return;
//}

//try (FileWriter fw = new FileWriter(jsonPath, false)) {
//    fw.write(gson.toJson(dirJson));
//} catch (Exception e) {
//    e.printStackTrace();
//    JOptionPane.showMessageDialog(this, "Error guardando el directorio.", "Error", JOptionPane.ERROR_MESSAGE);
//    return;
//}

    JOptionPane.showMessageDialog(this, "Directorio renombrado correctamente a:\n" + newName, "Éxito", JOptionPane.INFORMATION_MESSAGE);

    newDirectoryName.setText("");
    treeManager.refresh();
        });
    }//GEN-LAST:event_updDirActionPerformed

    private void newDirectoryNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newDirectoryNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newDirectoryNameActionPerformed

    private void createDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDirActionPerformed
        String nameDir = directoryName.getText().toUpperCase().strip();
        if (nameDir.isEmpty()) {
            // Validación para que el nombre no sea vacío.
            javax.swing.JOptionPane.showMessageDialog(this, "Ingresa un nombre.");
            return;
        }

        // Crear directorio
        Directory parent = (selectedDirectory != null) ? selectedDirectory : currentDirectory;
        Directory newDir = fileSystem.addDirectory(nameDir, parent, System.getProperty("user.name"));

        // Actualizar el JTree
        treeManager.refresh();

        JOptionPane.showMessageDialog(this, "Directorio '" + nameDir + "' creado con éxito.");

        // Limpiar el campo
        directoryName.setText("");
        
    }//GEN-LAST:event_createDirActionPerformed

    private void directoryNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_directoryNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_directoryNameActionPerformed

    private void showTreeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showTreeActionPerformed
        // TODO add your handling code here:
        treeManager.refresh();
        treeManager.showTree();
    }//GEN-LAST:event_showTreeActionPerformed

    private void colorCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorCmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorCmbActionPerformed

    private void dirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dirButtonActionPerformed
        // TODO add your handling code here:
        treeManager.openDirectoryChooser(dir -> {
            selectedDirectory = dir;
            JOptionPane.showMessageDialog(this,
                    "Directorio seleccionado:\n" + dir.getRute(),
                    "Directorio elegido",
                    JOptionPane.INFORMATION_MESSAGE);
        });
    }//GEN-LAST:event_dirButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        treeManager.openDirectoryChooser(dir -> {
            selectedDirectory = dir;
            JOptionPane.showMessageDialog(this,
                    "Directorio seleccionado:\n" + dir.getRute(),
                    "Directorio elegido",
                    JOptionPane.INFORMATION_MESSAGE);
        });
    }//GEN-LAST:event_jButton2ActionPerformed

    private void selArchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selArchActionPerformed
        // TODO add your handling code here:
        treeManager.openFileChooser((dir, file) -> {
            dirOfFileToDelete = dir;
            fileToDelete = file;

            JOptionPane.showMessageDialog(
                    this,
                    "Archivo seleccionado:\n" + file.getName()
                    + "\nDirectorio: " + dir.getRute(),
                    "Archivo a eliminar",
                    JOptionPane.INFORMATION_MESSAGE
            );
        });
    }//GEN-LAST:event_selArchActionPerformed

    private void delArchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delArchActionPerformed
        if (fileToDelete == null || dirOfFileToDelete == null) {
    JOptionPane.showMessageDialog(
            this,
            "Primero selecciona un archivo a eliminar.",
            "Ningún archivo seleccionado",
            JOptionPane.WARNING_MESSAGE
    );
    return;
}

String user = System.getProperty("user.name");
boolean ok = fileSystem.deleteFile(dirOfFileToDelete, fileToDelete, user);

if (ok) {
    String path = fileSystem.getLastLoadedJsonPath();
    if (path != null) {
        fileSystem.saveState(path);   // <-- Sobrescribe el JSON original
    }
    JOptionPane.showMessageDialog(
            this,
            "Archivo '" + fileToDelete.getName() + "' eliminado correctamente.",
            "Éxito",
            JOptionPane.INFORMATION_MESSAGE
    );

    // limpiar selección
    fileToDelete = null;
    dirOfFileToDelete = null;

    // refrescar árbol visual
    treeManager.refresh();

} else {
    JOptionPane.showMessageDialog(
            this,
            "No se pudo eliminar el archivo.",
            "Error",
            JOptionPane.ERROR_MESSAGE
    );
}

    }//GEN-LAST:event_delArchActionPerformed

    private void selDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selDirActionPerformed
        // TODO add your handling code here:
        treeManager.openDirectoryChooser(dir -> {
            dirToDelete = dir;

            JOptionPane.showMessageDialog(
                    this,
                    "Directorio seleccionado para eliminar:\n" + dir.getRute(),
                    "Directorio seleccionado",
                    JOptionPane.INFORMATION_MESSAGE
            );
        });
    }//GEN-LAST:event_selDirActionPerformed

    private void delDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delDirActionPerformed
       if (dirToDelete == null) {
    JOptionPane.showMessageDialog(
            this,
            "Primero selecciona un directorio a eliminar.",
            "Ningún directorio seleccionado",
            JOptionPane.WARNING_MESSAGE
    );
    return;
}

// Evitar borrar la raíz
if (dirToDelete == fileSystem.getRoot()) {
    JOptionPane.showMessageDialog(
            this,
            "No se puede eliminar el directorio raíz.",
            "Operación no permitida",
            JOptionPane.ERROR_MESSAGE
    );
    return;
}

int confirm = JOptionPane.showConfirmDialog(
        this,
        "¿Seguro que deseas eliminar el directorio:\n" + dirToDelete.getRute()
        + "\n y todo su contenido?",
        "Confirmar eliminación",
        JOptionPane.YES_NO_OPTION
);

if (confirm != JOptionPane.YES_OPTION) return;

String user = System.getProperty("user.name");
boolean ok = fileSystem.deleteDirectory(dirToDelete, user);

if (ok) {

    // ===============================
    //   ELIMINAR JSON DE /versions
    // ===============================
    String versionsPath = "C:/Users/58414/Documents/GitHub/Project2OS/Project2OS/versions";
    File versionsFolder = new File(versionsPath);

    if (versionsFolder.exists() && versionsFolder.isDirectory()) {

        File[] files = versionsFolder.listFiles((dir, name) -> name.endsWith(".json"));

        if (files != null) {
            for (File f : files) {

                try (FileReader reader = new FileReader(f)) {

                    JsonObject rootJson = JsonParser.parseReader(reader).getAsJsonObject();
                    JsonObject rootDirJson = rootJson.getAsJsonObject("rootDirectory");

                    if (rootDirJson == null) continue;

                    // -----------------------------------------
                    // LAMBDA RECURSIVA PARA BUSCAR EL DIRECTORIO
                    // -----------------------------------------
                    final boolean[] found = { false };

                    // Declaramos la lambda en un array para permitir recursión
                    final java.util.function.Consumer<JsonObject>[] search = new java.util.function.Consumer[1];

                    search[0] = (JsonObject obj) -> {
                        if (found[0]) return;

                        String name = obj.get("name").getAsString();
                        if (name.equals(dirToDelete.getName())) {
                            found[0] = true;
                            return;
                        }

                        if (obj.has("subdirectories")) {
                            JsonArray subs = obj.getAsJsonArray("subdirectories");
                            for (JsonElement e : subs) {
                                search[0].accept(e.getAsJsonObject());
                                if (found[0]) return;
                            }
                        }
                    };
                    search[0].accept(rootDirJson);

                    // Si lo contiene → eliminar archivo JSON
                    if (found[0]) {
                        reader.close(); // cerrar para evitar bloqueo en Windows
                        f.delete();
                    }

                } catch (Exception e) {
                    // JSON corrupto o inválido → ignorarlo
                }
            }
        }
    }

    JOptionPane.showMessageDialog(
            this,
            "Directorio eliminado correctamente.",
            "Éxito",
            JOptionPane.INFORMATION_MESSAGE
    );

    dirToDelete = null;
    treeManager.refresh();

} else {

    JOptionPane.showMessageDialog(
            this,
            "No se pudo eliminar el directorio.",
            "Error",
            JOptionPane.ERROR_MESSAGE
    );
}


    }//GEN-LAST:event_delDirActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        FilesTable win = new FilesTable(fileSystem);
        win.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        BlocksWindow bw = new BlocksWindow(fileSystem);
        bw.setVisible(true);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
    JFileChooser chooser = new JFileChooser("versions/");
    chooser.setDialogTitle("Selecciona la versión del sistema");
    chooser.setFileFilter(new FileNameExtensionFilter("JSON Files", "json"));

    int result = chooser.showOpenDialog(this);

    if (result == JFileChooser.APPROVE_OPTION) {
        File selectedFile = chooser.getSelectedFile();

        FileSystem loaded = FileSystem.loadState(selectedFile.getAbsolutePath());
        if (loaded != null) {
        this.fileSystem = loaded;
        treeManager.setFileSystem(loaded);   // <-- ACTUALIZA TREE MANAGER
        JOptionPane.showMessageDialog(this, "Versión cargada correctamente.");
    } else {
        JOptionPane.showMessageDialog(this, "Error cargando versión.");
    }
    }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
  
        try {
        String timestamp = new SimpleDateFormat("yyyyMMdd_HHmmss").format(new Date());
        String filename = "FilesState_" + timestamp + ".json";
        fileSystem.saveState("versions/" + filename);

        JOptionPane.showMessageDialog(
                this,
                "Versión del sistema guardada correctamente.",
                "Éxito",
                JOptionPane.INFORMATION_MESSAGE
        );

    } catch (Exception e) {
        JOptionPane.showMessageDialog(
                this,
                "Error al guardar el estado: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE
        );
        e.printStackTrace();
    }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //java.awt.EventQueue.invokeLater(new Runnable() {
            //public void run() {
                //new Admin().setVisible(true);
           //}
        //});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> colorCmb;
    private javax.swing.JButton createDir;
    private javax.swing.JButton delArch;
    private javax.swing.JButton delDir;
    private javax.swing.JButton dirButton;
    private javax.swing.JTextField directoryName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox<String> levelComb;
    private javax.swing.JTextField nameFile;
    private javax.swing.JTextField newDirectoryName;
    private javax.swing.JTextField newNameFile;
    private javax.swing.JButton selArch;
    private javax.swing.JButton selDir;
    private javax.swing.JButton showTree;
    private javax.swing.JSpinner sizeFile;
    private javax.swing.JButton updArch;
    private javax.swing.JButton updDir;
    // End of variables declaration//GEN-END:variables
}
