/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Process.Process;
import SYS.*;
import Scheduler.*;
import DS.*;
import Storage.DiskRequest;
import Config.AppContext;
import java.util.concurrent.atomic.AtomicInteger;
import javax.swing.* ;


/**
 *
 * @author Gabriel Flores
 */
public class User extends javax.swing.JFrame {
    
    private TreeManager treeManager;
    private FileSystem fileSystem;
    private DiskScheduler diskScheduler;
    private final AtomicInteger nextId = new AtomicInteger(1);
    private LinkedList<Process> processList;
    private Directory selectedDirectoryForCreate;

    /**
     * Creates new form User
     */
    public User(TreeManager treeManager) {
        this.treeManager = treeManager;
        this.fileSystem = AppContext.FILE_SYSTEM;
        this.diskScheduler = AppContext.DISK_SCHEDULER;
        
        initComponents();
        
        actualizarCamposSegunOperacion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        createProcess = new javax.swing.JButton();
        planningAlgorithm = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        opComb = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        archLoc = new javax.swing.JButton();
        archName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        diskSize = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listP = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Modo Usuario");

        jButton1.setText("Ver Sistema");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Escoger Modo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Crear proceso", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        createProcess.setText("Crear proceso");
        createProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProcessActionPerformed(evt);
            }
        });

        planningAlgorithm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIFO", "SSTF", "SCAN", "C-SCAN" }));
        planningAlgorithm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                planningAlgorithmActionPerformed(evt);
            }
        });

        jLabel8.setText("Políticas generadas:");

        opComb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Leer", "Crear", "Actualizar", "Eliminar" }));
        opComb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opCombActionPerformed(evt);
            }
        });

        jLabel9.setText("Operacion:");

        archLoc.setText("Ubicación del Archivo");
        archLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                archLocActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre Archivo:");

        jLabel3.setText("Tamaño:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(planningAlgorithm, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(diskSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(opComb, 0, 245, Short.MAX_VALUE)
                                .addComponent(archName)))
                        .addGap(355, 355, 355))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(archLoc))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(createProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opComb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(archLoc)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(archName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(diskSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(planningAlgorithm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addComponent(createProcess)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        listP.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lista de procesos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        javax.swing.GroupLayout listPLayout = new javax.swing.GroupLayout(listP);
        listP.setLayout(listPLayout);
        listPLayout.setHorizontalGroup(
            listPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 421, Short.MAX_VALUE)
        );
        listPLayout.setVerticalGroup(
            listPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(listP);

        jButton4.setText("Siguiente solicitud");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton4)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(171, 171, 171))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(351, 351, 351))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MainFrame main = new MainFrame();
        this.setVisible(false);
        main.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        treeManager.refresh();
        treeManager.showTree();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void createProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProcessActionPerformed
        String opStr = (String) opComb.getSelectedItem();
        if (opStr == null) {
            JOptionPane.showMessageDialog(this, "Selecciona una operación (CRUD).");
            return;
        }

        if (opStr.equalsIgnoreCase("Crear")) {
            crearProcesoCreate();
        } else if (opStr.equalsIgnoreCase("Leer")) {
            crearProcesoRead();
        } else if (opStr.equalsIgnoreCase("Actualizar")) {
            crearProcesoUpdate();
        } else if (opStr.equalsIgnoreCase("Eliminar")) {
            crearProcesoDelete();
        }
    }//GEN-LAST:event_createProcessActionPerformed

    private void planningAlgorithmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_planningAlgorithmActionPerformed
        // TODO add your handling code here:
        String selected = (String) planningAlgorithm.getSelectedItem();

        switch (selected) {
            case "FIFO" ->
                AppContext.DISK_SCHEDULER.setAlgorithm(new FIFO());
            case "SSTF" ->
                AppContext.DISK_SCHEDULER.setAlgorithm(new SSTF());
            case "SCAN" -> {
                int max = AppContext.FILE_SYSTEM.getDisk().getTotalBlocks() - 1;
                AppContext.DISK_SCHEDULER.setAlgorithm(new SCAN(max));
            }
            case "C-SCAN" -> {
                int max = AppContext.FILE_SYSTEM.getDisk().getTotalBlocks() - 1;
                AppContext.DISK_SCHEDULER.setAlgorithm(new CSCAN(max));
            }
        }
        
        AppContext.DISK_SCHEDULER.reorder();

        refreshQueuePanel();

        System.out.println("→ Política cambiada a " + selected);
    }//GEN-LAST:event_planningAlgorithmActionPerformed

    private void archLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_archLocActionPerformed
        // TODO add your handling code here:
        String op = (String) opComb.getSelectedItem();
        if (op == null || !op.equalsIgnoreCase("CREAR")) {
            JOptionPane.showMessageDialog(this,
                    "La ubicación solo aplica para CREAR.",
                    "Operación inválida",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        treeManager.openDirectoryChooser(dir -> {
            selectedDirectoryForCreate = dir;
            JOptionPane.showMessageDialog(
                    this,
                    "Directorio seleccionado:\n" + dir.getRute(),
                    "Directorio elegido",
                    JOptionPane.INFORMATION_MESSAGE
            );
        });
    }//GEN-LAST:event_archLocActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        AppContext.DISK_SCHEDULER.dispatch();
        refreshQueuePanel();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void opCombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opCombActionPerformed
        // TODO add your handling code here:
        actualizarCamposSegunOperacion();
    }//GEN-LAST:event_opCombActionPerformed

    
    private void actualizarCamposSegunOperacion() {
        String op = (String) opComb.getSelectedItem();
        if (op == null) {
            return;
        }

        boolean isCreate = op.equalsIgnoreCase("CREAR");
        boolean isUpdate = op.equalsIgnoreCase("ACTUALIZAR");

        // Botón de ubicación solo tiene sentido para CREAR
        archLoc.setEnabled(isCreate);

        // Nombre de archivo: se usa en CREAR y en ACTUALIZAR (nuevo nombre)
        archName.setEnabled(isCreate || isUpdate);

        // Tamaño solo para CREAR
        diskSize.setEnabled(isCreate);
    }
    
    private void crearProcesoCreate() {
        String name = archName.getText().trim().toUpperCase();
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingresa un nombre de archivo.");
            return;
        }

        int size;
        try {
            size = ((Number) diskSize.getValue()).intValue();
        } catch (ClassCastException e) {
            JOptionPane.showMessageDialog(this, "El tamaño debe ser un entero.");
            return;
        }
        if (size <= 0) {
            JOptionPane.showMessageDialog(this, "El tamaño debe ser mayor que 0.");
            return;
        }

        // por ahora, digamos que todos los archivos creados por usuario son privados:
        boolean isPublic = false;  // cuando creas el archivo real lo pasas a addFile

        Directory dir = selectedDirectoryForCreate;
        if (dir == null) {
            dir = fileSystem.getRoot();
        }

        // Creamos el Process lógico
        int pID = nextId.getAndIncrement();
        Process p = new Process(
                pID,
                "CREATE_" + name,
                Process.OperationType.Create,
                0, // diskPosition: para CREATE puedes dejar 0
                null, // targetFile: todavía no existe
                Process.Status.Ready
        );

        // DiskRequest para CREATE: targetBlock lo ponemos 0 (no importa mucho en FIFO)
        DiskRequest req = new DiskRequest(
                p,
                archName.getText(),
                size,
                "Azul",
                dir,
                0 // targetBlock
        );

        AppContext.DISK_SCHEDULER.submit(req);

        JOptionPane.showMessageDialog(this,
                "Proceso de CREACIÓN creado y solicitud encolada.",
                "Proceso creado",
                JOptionPane.INFORMATION_MESSAGE);

        refreshQueuePanel();
    }
    
    private void crearProcesoRead() {
        // Abrimos el chooser de archivo
        treeManager.openFileChooser((dir, file) -> {
            if (dir == null || file == null) {
                return;
            }

            int pid = nextId.getAndIncrement();
            int block = file.getFirstBlock();

            Process p = new Process(
                    pid,
                    "READ_" + file.getName(),
                    Process.OperationType.Read,
                    block,
                    file,
                    Process.Status.Ready
            );

            DiskRequest req = new DiskRequest(
                    p,
                    DiskRequest.Type.Read,
                    file,
                    dir,
                    block // targetBlock = primer bloque del archivo
            );

            AppContext.DISK_SCHEDULER.submit(req);

            JOptionPane.showMessageDialog(this,
                    "Proceso de LECTURA creado para: " + file.getName(),
                    "Proceso creado",
                    JOptionPane.INFORMATION_MESSAGE);

            refreshQueuePanel();
        });
    }
    
    private void crearProcesoUpdate() {
        String newName = archName.getText().trim().toUpperCase();
        if (newName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingresa el nuevo nombre del archivo.");
            return;
        }

        treeManager.openFileChooser((dir, file) -> {
            if (dir == null || file == null) {
                return;
            }

            int pid = nextId.getAndIncrement();
            int block = file.getFirstBlock();

            Process p = new Process(
                    pid,
                    "UPDATE_" + file.getName(),
                    Process.OperationType.Update,
                    block,
                    file,
                    Process.Status.Ready
            );

            // OJO: aquí usamos el constructor de DiskRequest de operaciones con file
            DiskRequest req = new DiskRequest(
                    p,
                    DiskRequest.Type.Update,
                    file,
                    dir,
                    block
            );
            // pero necesitamos que el DiskRequest sepa el nuevo nombre → seteamos el fileName:
            req.setFileName(newName);

            AppContext.DISK_SCHEDULER.submit(req);

            JOptionPane.showMessageDialog(this,
                    "Proceso de UPDATE creado para: " + file.getName()
                    + "\nNuevo nombre: " + newName,
                    "Proceso creado",
                    JOptionPane.INFORMATION_MESSAGE);

            refreshQueuePanel();
        });
    }
    
    private void crearProcesoDelete() {
        treeManager.openFileChooser((dir, file) -> {
            if (dir == null || file == null) {
                return;
            }

            int pid = nextId.getAndIncrement();
            int block = file.getFirstBlock();

            Process p = new Process(
                    pid,
                    "DELETE_" + file.getName(),
                    Process.OperationType.Delete,
                    block,
                    file,
                    Process.Status.Ready
            );

            DiskRequest req = new DiskRequest(
                    p,
                    DiskRequest.Type.Delete,
                    file,
                    dir,
                    block
            );

            AppContext.DISK_SCHEDULER.submit(req);

            JOptionPane.showMessageDialog(this,
                    "Proceso de DELETE creado para: " + file.getName(),
                    "Proceso creado",
                    JOptionPane.INFORMATION_MESSAGE);

            refreshQueuePanel();
        });
    }
    
    private javax.swing.JPanel buildRequestCard(DiskRequest req) {
        javax.swing.JPanel card = new javax.swing.JPanel();
        card.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5),
                javax.swing.BorderFactory.createLineBorder(java.awt.Color.GRAY, 1)
        ));
        card.setLayout(new java.awt.GridLayout(3, 1));

        Process p = req.getProcess();

        String name = (p != null) ? p.getProcessName() : "(sin nombre)";
        String op = (req.getType() != null) ? req.getType().name() : "(desconocida)";
        String state = (p != null && p.getStatus() != null) ? p.getStatus().name() : "(desconocido)";

        javax.swing.JLabel lblName = new javax.swing.JLabel("Proceso: " + name);
        javax.swing.JLabel lblOp = new javax.swing.JLabel("Operación: " + op);
        javax.swing.JLabel lblState = new javax.swing.JLabel("Estado: " + state);

        card.add(lblName);
        card.add(lblOp);
        card.add(lblState);

        return card;
    }
    
    private void refreshQueuePanel() {
        listP.removeAll();
        listP.setLayout(new javax.swing.BoxLayout(listP, javax.swing.BoxLayout.Y_AXIS));

        Queue.Node<DiskRequest>[] nodes = AppContext.DISK_SCHEDULER.getQueue().getAllNodes();
        if (nodes != null) {
            for (Queue.Node<DiskRequest> node : nodes) {
                DiskRequest req = node.getData();
                javax.swing.JPanel card = buildRequestCard(req);   // CAMBIO: usamos tarjetas
                listP.add(card);
            }
        }

        listP.revalidate();
        listP.repaint();
    }

    private String formatDiskRequest(DiskRequest req) {
        String procName = (req.getProcess() != null) ? req.getProcess().getProcessName() : "Proc?";
        String type = req.getType().name();
        String file = (req.getFile() != null) ? req.getFile().getName() : req.getFileName();

        return "[PID=" + (req.getProcess() != null ? req.getProcess().getID() : "?")
                + "] (" + type + ") "
                + (file != null ? file : "<sin archivo>")
                + " @ bloque " + req.getTargetBlock();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new User().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton archLoc;
    private javax.swing.JTextField archName;
    private javax.swing.JButton createProcess;
    private javax.swing.JSpinner diskSize;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JPanel listP;
    private javax.swing.JComboBox<String> opComb;
    private javax.swing.JComboBox<String> planningAlgorithm;
    // End of variables declaration//GEN-END:variables
}
